library(RUnit)
source("tms-chd1.R")
trenaProject <- TrenaProjectErythropoiesis()
x <- TMS$new("CHD1", trenaProject)
x$addGeneHancer()
tbl.gh <- x$getGeneHancer()
checkEquals(dim(tbl.gh), c(25, 16))
tbl.ghRegion <- x$getGeneHancerRegion()
checkEquals(tbl.ghRegion$start, min(tbl.gh$start) - 1000)
checkEquals(tbl.ghRegion$end, max(tbl.gh$end) + 1000)
x$addOpenChromatin()
tbl.oc <- x$getOpenChromatin()
checkEquals(dim(tbl.oc), c(88, 7))
x$addAndScoreFimoTFBS(1e-5)
tbl.tms <- x$getTfTable()
checkEquals(dim(tbl.tms), c(48, 16))
x$addRBP()
tbl.rbp <- x$getRbpTable()
getExpressionMatrixNames(trenaProject)
mtx <- getExpressionMatrix(trenaProject,
                           "brandLabDifferentiationTimeCourse-27171x28-namesCorrected")
x$add.tf.mrna.correlations(mtx, featureName="cor.all")
tbl.tms <- x$getTfTable()
checkTrue("cor.all" %in% colnames(tbl.tms))
fivenum(tbl.tms$cor.all)
x$add.rbp.mrna.correlations(mtx, featureName="cor.all")
tbl.rbp <- x$getRbpTable()
checkTrue("cor.all" %in% colnames(tbl.rbp))
fivenum(tbl.rbp$cor.all)


